on:
  push:
    tags:
      - "*"

env:
  NODE_VERSION: "14.x"

jobs:
  build-and-deploy-app:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: "Install dependencies"
        run: npm i
      - name: "Build app"
        run: npm run build --prod --aot
      - name: "Deploy to engine app"
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          project: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_APPENGINE_SERVICE_KEY }}
          deliverables: app.yaml
